try:
    x = 1+2
    print(x)
except:
    print("iSSUE OCCURED DURING OPERATION")
finally:
    print("The addition was made, no errors")
